// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzjbovwgydpmwztuxoel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16amJvdndneWRwbXd6dHV4b2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTE3NzgsImV4cCI6MjA2NDY4Nzc3OH0.bHkBqz7SQ5uqKDGCJO1Dt1YBhL0UG556LX4llCwtS-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);